service: skunkworks

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

# you can overwrite defaults here
#  stage: dev
  region: us-west-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:Query
        - dynamodb:UpdateItem
      Resource:
      - "arn:aws:dynamodb:*:*:table/users"

functions:
  users:
    handler: handler.userCreate
    events:
      - http:
          path: users
          method: post

resources:
  Resources:
    Skunkworks:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "email"
          AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
          - AttributeName: "email"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "users"